In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=b"hai gunnu this is vamsi krishna"
c=np.frombuffer(b,dtype="S1",count=5,offset=5)

In [16]:
print(c)

[b'u' b'n' b'n' b'u' b' ']


In [17]:
a=[1,2,3,4,5]

In [20]:
np.fromiter(a,dtype='S1',count=3)

array([b'1', b'2', b'3'], dtype='|S1')

In [23]:
a=np.zeros([3,4])

In [24]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.full([3,3],10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [29]:
np.random.rand(2,3)

array([[0.67287189, 0.00689796, 0.94158115],
       [0.64567563, 0.24195398, 0.08344776]])

In [30]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
#numerical ranges

In [33]:
#arange()


In [35]:
a=np.arange(10,30,1,dtype=int)

In [36]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [4]:
np.linspace(10,100,10,dtype=int,endpoint=False,retstep=True)

NameError: name 'np' is not defined

In [2]:
a=np.arange(10,100,9,dtype=int)
print(a)

NameError: name 'np' is not defined

In [3]:
np.logspace(1,10,10,base=2)

NameError: name 'np' is not defined

In [ ]:
np.logspace(1,10,10,base=10)

In [ ]:
a

In [ ]:
hii

In [ ]:
print(a)

In [5]:
import numpy as np
a=np.array(4)
print(a)

4


In [6]:
import requests
r=requests.get("")

MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

In [9]:
import numpy as np
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [12]:
np.logspace(1,10,10,base=10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [13]:
a=np.arange(1,10,1)

In [14]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.size(a)

9

In [20]:
a.dtype

dtype('int32')

a

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a=np.arange(1,21,1)

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [29]:
a[0]

1

In [31]:
a[0][1]

IndexError: invalid index to scalar variable.

In [32]:
print(a.ndim)

1


In [33]:
a=np.array([[[1,2,3],[4,5,6]],[[2,32,3],[2,5,3]]])

In [34]:
a.ndim

3

In [37]:
a[1][1][1]

5

In [38]:
a[2:5]

array([], shape=(0, 2, 3), dtype=int32)

In [39]:
a=np.arange(1,30,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [40]:
a[2:5]

array([5, 7, 9])

In [41]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [42]:
b=np.arange(30,40,2)

In [43]:
b

array([30, 32, 34, 36, 38])

In [45]:
b=np.copy(a)

In [46]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [49]:
a[3]=200

In [50]:
a

array([  1,   3,   5, 200,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29])

In [51]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [54]:
c=a.view()

In [55]:
c

array([  1,   3,   5, 200,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29])

In [56]:
a[6]=500

In [57]:
a

array([  1,   3,   5, 200,   9,  11, 500,  15,  17,  19,  21,  23,  25,
        27,  29])

In [58]:
c

array([  1,   3,   5, 200,   9,  11, 500,  15,  17,  19,  21,  23,  25,
        27,  29])

In [60]:
a=np.array([10,9,8,7,6,5,4,3,2,1])
b=np.sort(a)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
c=np.sort(b,ascending=False)

TypeError: sort() got an unexpected keyword argument 'ascending'

In [71]:
d=np.dtype([('name',"S1"),("Idno:","int32")])
marks=np.array([("krishna",100),("gunnu",90),("vamsi",99)],dtype=d)

In [72]:
marks

array([(b'k', 100), (b'g',  90), (b'v',  99)],
      dtype=[('name', 'S1'), ('Idno:', '<i4')])

In [73]:
np.sort(marks,order="name")

array([(b'g',  90), (b'k', 100), (b'v',  99)],
      dtype=[('name', 'S1'), ('Idno:', '<i4')])

In [75]:
np.sort(marks,order="Idno:")

array([(b'g',  90), (b'v',  99), (b'k', 100)],
      dtype=[('name', 'S1'), ('Idno:', '<i4')])

In [76]:
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [77]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
b=np.array([11,12])
b

array([11, 12])

In [84]:
b=np.append(a,b).reshape(2,6)

In [85]:
b

array([[10,  9,  8,  7,  6,  5],
       [ 4,  3,  2,  1, 11, 12]])

In [92]:
c=np.insert(b,3,[43,44])

In [93]:
c

array([10,  9,  8, 43, 44,  7,  6,  5,  4,  3,  2,  1, 11, 12])

In [91]:
np.delete(c,5)

array([10,  9,  8, 43, 44,  6,  5,  4,  3,  2,  1, 11, 12])

In [114]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim
a.shape

(2, 3)

In [115]:
b=np.array([[11,12,13],[14,15,16]])
b.ndim
b.shape

(2, 3)

In [116]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [132]:
np.stack((a,b))

ValueError: all input arrays must have the same shape

In [133]:
a.shape

(2, 2, 3)

In [127]:
res

NameError: name 'res' is not defined

In [137]:
a=np.array([[1,2,3],[11,12,13]])
b=np.array([[4,5,6],[14,15,16]])

In [144]:
np.stack((a,b),axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [145]:
np.stack((a,b),axis=0)

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [14, 15, 16]]])

In [141]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 4,  5,  6],
       [14, 15, 16]])

In [142]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [146]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 4,  5,  6],
       [14, 15, 16]])

In [148]:
np.hstack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [149]:
a=np.arange(10,110,10)

In [150]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [151]:
np.split(a,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [155]:
np.split(a,(4,3))

[array([10, 20, 30, 40]),
 array([], dtype=int32),
 array([ 40,  50,  60,  70,  80,  90, 100])]

In [158]:
np.split(a,[6,6])

[array([10, 20, 30, 40, 50, 60]),
 array([], dtype=int32),
 array([ 70,  80,  90, 100])]

In [159]:
a=np.arange(10,130,10)

In [160]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [168]:
np.where(a==30)

(array([2], dtype=int64),)

In [165]:
np.where(a%20==0)

(array([ 1,  3,  5,  7,  9, 11], dtype=int64),)

In [169]:
np.searchsorted(a,30)

2

In [170]:
np.searchsorted(a,[10,20])

array([0, 1], dtype=int64)

In [171]:
a=np.array([[1,1,1],[1,1,1]])

In [173]:
b=np.array([[1,1,1],[1,1,1]])

In [174]:
np.add(a,b)

array([[2, 2, 2],
       [2, 2, 2]])

In [177]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0]])

In [178]:
np.multiply(a,b)

array([[1, 1, 1],
       [1, 1, 1]])

In [194]:
np.divide(a,b)

array([[0.66666667, 0.66666667, 0.66666667],
       [0.66666667, 0.66666667, 0.66666667]])

In [196]:
np.array_equal(a,b)

False

In [181]:
np.exp(a)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [182]:
np.sqrt(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [188]:
a=np.full([2,3],2)

In [186]:
b=np.full([2,3],3)

In [189]:
np.add(a,b)

array([[5, 5, 5],
       [5, 5, 5]])

In [191]:
np.sqrt(a)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [192]:
np.array_equal(a,b)

False

In [193]:
a==b

array([[False, False, False],
       [False, False, False]])

In [197]:
a=np.full([2,3],2)

In [198]:
b=np.full([2,3],2)

In [199]:
a==b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [206]:
a=np.array([[10,20],[30,40],[50,60]]).reshape(3,2)
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [201]:
np.min(a)

10

In [202]:
np.min(a,axis=0)

array([10, 20])

In [204]:
np.min(a,axis=1)

array([10, 30, 50])

In [207]:
import pandas as pd

In [208]:
d=pd.read_excel("C:\\Users\\MOUNIKA\\Desktop\\numpy\\marks.xlsx")

In [209]:
df=pd.DataFrame(d)

In [210]:
df

Name  Roll_no  Telugu  English  Maths  Science  Social
0      krishna       11      90       40     50       60      55
1        gunnu       12      90       41     51       61      56
2        mouni       13      30       42     52       62      57
3        vamsi       14      40       43     53       63      58
4      manohar       15      20       44     54       64      59
5        laxmi       16      29       45     55       65      60
6        vijay       17      49       46     56       66      61
7       rajesh       18      48       47     57       67      62
8        krish       19      59       48     58       68      63
9      mounika       20      69       49     59       69      64
10         sai       21      60       50     60       70      65
11       padma       22      70       51     61       71      66
12       divya       23      71       52     62       72      67
13      sharmi       24      72       53     63       73      68
14        manu       25      73       54     64       74      69
15       kumar       26      74       55     65       75      70
16        anju       27      75       56     66       76      71
17     keerthi       28      76       57     67       77      72
18     thanuja       29      77       58     68       78      73
19       priya       30      78       59     69       79      74
20     likitha       31      79       60     70       80      75
21     nikitha       32      80       61     71       81      76
22  prathyusha       33      81       62     72       82      77
23       bindu       34      82       63     73       83      78
24      sandya       35      83       64     74       84      79
25      kumari       36      84       65     75       85      80
26   sai priya       37      85       66     76       86      81
27       kiran       38      86       67     77       87      82
28      charan       39      87       68     78       88      83
29     chnadra       40      88       69     79       89      84
30    kamakshi       41      89       70     80       90      85
31     sirisha       42      90       71     81       91      86
32      jyothi       43      91       72     82       92      87
33      kusuma       44      92       73     83       93      88

In [211]:
#Creating dataframes using dictionaries

In [222]:
dic={"Name":["krishna","gunnu","mouni"],"Roll_no":[101,102,103],"Marks":[100,20,40]}

In [223]:
dfdic=pd.DataFrame(dic)

In [217]:
dfdic

Name  Roll_no  Marks
0  krishna      101    100
1    gunnu      102     20
2    mouni      103     40

In [224]:
l=[('krishna',101,100),("gunnu",102,20),("mouni",103,40)]

In [225]:
l

[('krishna', 101, 100), ('gunnu', 102, 20), ('mouni', 103, 40)]

In [229]:
dfl=pd.DataFrame(l)

In [230]:
dfl

0    1    2
0  krishna  101  100
1    gunnu  102   20
2    mouni  103   40

In [231]:
d=pd.read_excel("C:\\Users\\MOUNIKA\\Desktop\\numpy\\marks.xlsx")
df=pd.DataFrame(d)

In [232]:
df

Name  Roll_no  Telugu  English  Maths  Science  Social
0      krishna       11      90       40     50       60      55
1        gunnu       12      90       41     51       61      56
2        mouni       13      30       42     52       62      57
3        vamsi       14      40       43     53       63      58
4      manohar       15      20       44     54       64      59
5        laxmi       16      29       45     55       65      60
6        vijay       17      49       46     56       66      61
7       rajesh       18      48       47     57       67      62
8        krish       19      59       48     58       68      63
9      mounika       20      69       49     59       69      64
10         sai       21      60       50     60       70      65
11       padma       22      70       51     61       71      66
12       divya       23      71       52     62       72      67
13      sharmi       24      72       53     63       73      68
14        manu       25      73       54     64       74      69
15       kumar       26      74       55     65       75      70
16        anju       27      75       56     66       76      71
17     keerthi       28      76       57     67       77      72
18     thanuja       29      77       58     68       78      73
19       priya       30      78       59     69       79      74
20     likitha       31      79       60     70       80      75
21     nikitha       32      80       61     71       81      76
22  prathyusha       33      81       62     72       82      77
23       bindu       34      82       63     73       83      78
24      sandya       35      83       64     74       84      79
25      kumari       36      84       65     75       85      80
26   sai priya       37      85       66     76       86      81
27       kiran       38      86       67     77       87      82
28      charan       39      87       68     78       88      83
29     chnadra       40      88       69     79       89      84
30    kamakshi       41      89       70     80       90      85
31     sirisha       42      90       71     81       91      86
32      jyothi       43      91       72     82       92      87
33      kusuma       44      92       73     83       93      88

In [233]:
df.head()

Name  Roll_no  Telugu  English  Maths  Science  Social
0  krishna       11      90       40     50       60      55
1    gunnu       12      90       41     51       61      56
2    mouni       13      30       42     52       62      57
3    vamsi       14      40       43     53       63      58
4  manohar       15      20       44     54       64      59

In [235]:
df.tail(10)

Name  Roll_no  Telugu  English  Maths  Science  Social
24     sandya       35      83       64     74       84      79
25     kumari       36      84       65     75       85      80
26  sai priya       37      85       66     76       86      81
27      kiran       38      86       67     77       87      82
28     charan       39      87       68     78       88      83
29    chnadra       40      88       69     79       89      84
30   kamakshi       41      89       70     80       90      85
31    sirisha       42      90       71     81       91      86
32     jyothi       43      91       72     82       92      87
33     kusuma       44      92       73     83       93      88

In [236]:
df.describe()

Roll_no     Telugu    English      Maths    Science     Social
count  34.000000  34.000000  34.000000  34.000000  34.000000  34.000000
mean   27.500000  71.970588  56.500000  66.500000  76.500000  71.500000
std     9.958246  19.299058   9.958246   9.958246   9.958246   9.958246
min    11.000000  20.000000  40.000000  50.000000  60.000000  55.000000
25%    19.250000  69.250000  48.250000  58.250000  68.250000  63.250000
50%    27.500000  77.500000  56.500000  66.500000  76.500000  71.500000
75%    35.750000  85.750000  64.750000  74.750000  84.750000  79.750000
max    44.000000  92.000000  73.000000  83.000000  93.000000  88.000000

In [238]:
df.shape

(34, 7)

In [240]:
df[1:6:1]

Name  Roll_no  Telugu  English  Maths  Science  Social
1    gunnu       12      90       41     51       61      56
2    mouni       13      30       42     52       62      57
3    vamsi       14      40       43     53       63      58
4  manohar       15      20       44     54       64      59
5    laxmi       16      29       45     55       65      60

In [241]:
df["Telugu"]

0     90
1     90
2     30
3     40
4     20
5     29
6     49
7     48
8     59
9     69
10    60
11    70
12    71
13    72
14    73
15    74
16    75
17    76
18    77
19    78
20    79
21    80
22    81
23    82
24    83
25    84
26    85
27    86
28    87
29    88
30    89
31    90
32    91
33    92
Name: Telugu, dtype: int64

In [244]:
df[["Telugu","English"]][1:5]

Telugu  English
1      90       41
2      30       42
3      40       43
4      20       44

In [246]:
for rec in df.iterrows():
    print(rec)

(0, Name       krishna
Roll_no         11
Telugu          90
English         40
Maths           50
Science         60
Social          55
Name: 0, dtype: object)
(1, Name       gunnu
Roll_no       12
Telugu        90
English       41
Maths         51
Science       61
Social        56
Name: 1, dtype: object)
(2, Name       mouni
Roll_no       13
Telugu        30
English       42
Maths         52
Science       62
Social        57
Name: 2, dtype: object)
(3, Name       vamsi
Roll_no       14
Telugu        40
English       43
Maths         53
Science       63
Social        58
Name: 3, dtype: object)
(4, Name       manohar
Roll_no         15
Telugu          20
English         44
Maths           54
Science         64
Social          59
Name: 4, dtype: object)
(5, Name       laxmi
Roll_no       16
Telugu        29
English       45
Maths         55
Science       65
Social        60
Name: 5, dtype: object)
(6, Name       vijay
Roll_no       17
Telugu        49
English       46
Maths         56
S

In [247]:
df.loc[1]

Name       gunnu
Roll_no       12
Telugu        90
English       41
Maths         51
Science       61
Social        56
Name: 1, dtype: object

In [248]:
df.iloc[2]

Name       mouni
Roll_no       13
Telugu        30
English       42
Maths         52
Science       62
Social        57
Name: 2, dtype: object

In [256]:
df.iloc[1:5,[1,2]]

Roll_no  Telugu
1       12      90
2       13      30
3       14      40
4       15      20

In [251]:
df.iloc[1:10]

Name  Roll_no  Telugu  English  Maths  Science  Social
1    gunnu       12      90       41     51       61      56
2    mouni       13      30       42     52       62      57
3    vamsi       14      40       43     53       63      58
4  manohar       15      20       44     54       64      59
5    laxmi       16      29       45     55       65      60
6    vijay       17      49       46     56       66      61
7   rajesh       18      48       47     57       67      62
8    krish       19      59       48     58       68      63
9  mounika       20      69       49     59       69      64

In [258]:
df.loc[1:5,"Name":"Social"]

Name  Roll_no  Telugu  English  Maths  Science  Social
1    gunnu       12      90       41     51       61      56
2    mouni       13      30       42     52       62      57
3    vamsi       14      40       43     53       63      58
4  manohar       15      20       44     54       64      59
5    laxmi       16      29       45     55       65      60

In [263]:
df.iloc[1:5,1:7]

Roll_no  Telugu  English  Maths  Science  Social
1       12      90       41     51       61      56
2       13      30       42     52       62      57
3       14      40       43     53       63      58
4       15      20       44     54       64      59

In [261]:
df.shape

(34, 7)

In [265]:
df.iloc[[1,2,3]]

Name  Roll_no  Telugu  English  Maths  Science  Social
1  gunnu       12      90       41     51       61      56
2  mouni       13      30       42     52       62      57
3  vamsi       14      40       43     53       63      58

In [267]:
df.iloc[ : ,1:5]

Roll_no  Telugu  English  Maths
0        11      90       40     50
1        12      90       41     51
2        13      30       42     52
3        14      40       43     53
4        15      20       44     54
5        16      29       45     55
6        17      49       46     56
7        18      48       47     57
8        19      59       48     58
9        20      69       49     59
10       21      60       50     60
11       22      70       51     61
12       23      71       52     62
13       24      72       53     63
14       25      73       54     64
15       26      74       55     65
16       27      75       56     66
17       28      76       57     67
18       29      77       58     68
19       30      78       59     69
20       31      79       60     70
21       32      80       61     71
22       33      81       62     72
23       34      82       63     73
24       35      83       64     74
25       36      84       65     75
26       37      85       66     76
27       38      86       67     77
28       39      87       68     78
29       40      88       69     79
30       41      89       70     80
31       42      90       71     81
32       43      91       72     82
33       44      92       73     83

In [276]:
df.sort_values(["Name","Telugu"],ascending=[1,0])

Name  Roll_no  Telugu  English  Maths  Science  Social
16        anju       27      75       56     66       76      71
23       bindu       34      82       63     73       83      78
28      charan       39      87       68     78       88      83
29     chnadra       40      88       69     79       89      84
12       divya       23      71       52     62       72      67
1        gunnu       12      90       41     51       61      56
32      jyothi       43      91       72     82       92      87
30    kamakshi       41      89       70     80       90      85
17     keerthi       28      76       57     67       77      72
27       kiran       38      86       67     77       87      82
8        krish       19      59       48     58       68      63
0      krishna       11      90       40     50       60      55
15       kumar       26      74       55     65       75      70
25      kumari       36      84       65     75       85      80
33      kusuma       44      92       73     83       93      88
5        laxmi       16      29       45     55       65      60
20     likitha       31      79       60     70       80      75
4      manohar       15      20       44     54       64      59
14        manu       25      73       54     64       74      69
2        mouni       13      30       42     52       62      57
9      mounika       20      69       49     59       69      64
21     nikitha       32      80       61     71       81      76
11       padma       22      70       51     61       71      66
22  prathyusha       33      81       62     72       82      77
19       priya       30      78       59     69       79      74
7       rajesh       18      48       47     57       67      62
10         sai       21      60       50     60       70      65
26   sai priya       37      85       66     76       86      81
24      sandya       35      83       64     74       84      79
13      sharmi       24      72       53     63       73      68
31     sirisha       42      90       71     81       91      86
18     thanuja       29      77       58     68       78      73
3        vamsi       14      40       43     53       63      58
6        vijay       17      49       46     56       66      61

In [280]:
df["Marks"]=df["Telugu"]+df["English"]+df["Maths"]+df["Science"]+df["Social"]

In [281]:
df

Name  Roll_no  Telugu  English  Maths  Science  Social  Marks
0      krishna       11      90       40     50       60      55    295
1        gunnu       12      90       41     51       61      56    299
2        mouni       13      30       42     52       62      57    243
3        vamsi       14      40       43     53       63      58    257
4      manohar       15      20       44     54       64      59    241
5        laxmi       16      29       45     55       65      60    254
6        vijay       17      49       46     56       66      61    278
7       rajesh       18      48       47     57       67      62    281
8        krish       19      59       48     58       68      63    296
9      mounika       20      69       49     59       69      64    310
10         sai       21      60       50     60       70      65    305
11       padma       22      70       51     61       71      66    319
12       divya       23      71       52     62       72      67    324
13      sharmi       24      72       53     63       73      68    329
14        manu       25      73       54     64       74      69    334
15       kumar       26      74       55     65       75      70    339
16        anju       27      75       56     66       76      71    344
17     keerthi       28      76       57     67       77      72    349
18     thanuja       29      77       58     68       78      73    354
19       priya       30      78       59     69       79      74    359
20     likitha       31      79       60     70       80      75    364
21     nikitha       32      80       61     71       81      76    369
22  prathyusha       33      81       62     72       82      77    374
23       bindu       34      82       63     73       83      78    379
24      sandya       35      83       64     74       84      79    384
25      kumari       36      84       65     75       85      80    389
26   sai priya       37      85       66     76       86      81    394
27       kiran       38      86       67     77       87      82    399
28      charan       39      87       68     78       88      83    404
29     chnadra       40      88       69     79       89      84    409
30    kamakshi       41      89       70     80       90      85    414
31     sirisha       42      90       71     81       91      86    419
32      jyothi       43      91       72     82       92      87    424
33      kusuma       44      92       73     83       93      88    429

In [293]:
df["Percentage"]=0
df

Name  Roll_no  Telugu  English  Maths  Science  Social  Marks  \
0      krishna       11      90       40     50       60      55    295   
1        gunnu       12      90       41     51       61      56    299   
2        mouni       13      30       42     52       62      57    243   
3        vamsi       14      40       43     53       63      58    257   
4      manohar       15      20       44     54       64      59    241   
5        laxmi       16      29       45     55       65      60    254   
6        vijay       17      49       46     56       66      61    278   
7       rajesh       18      48       47     57       67      62    281   
8        krish       19      59       48     58       68      63    296   
9      mounika       20      69       49     59       69      64    310   
10         sai       21      60       50     60       70      65    305   
11       padma       22      70       51     61       71      66    319   
12       divya       23      71       52     62       72      67    324   
13      sharmi       24      72       53     63       73      68    329   
14        manu       25      73       54     64       74      69    334   
15       kumar       26      74       55     65       75      70    339   
16        anju       27      75       56     66       76      71    344   
17     keerthi       28      76       57     67       77      72    349   
18     thanuja       29      77       58     68       78      73    354   
19       priya       30      78       59     69       79      74    359   
20     likitha       31      79       60     70       80      75    364   
21     nikitha       32      80       61     71       81      76    369   
22  prathyusha       33      81       62     72       82      77    374   
23       bindu       34      82       63     73       83      78    379   
24      sandya       35      83       64     74       84      79    384   
25      kumari       36      84       65     75       85      80    389   
26   sai priya       37      85       66     76       86      81    394   
27       kiran       38      86       67     77       87      82    399   
28      charan       39      87       68     78       88      83    404   
29     chnadra       40      88       69     79       89      84    409   
30    kamakshi       41      89       70     80       90      85    414   
31     sirisha       42      90       71     81       91      86    419   
32      jyothi       43      91       72     82       92      87    424   
33      kusuma       44      92       73     83       93      88    429   

    Percentage  
0            0  
1            0  
2            0  
3            0  
4            0  
5            0  
6            0  
7            0  
8            0  
9            0  
10           0  
11           0  
12           0  
13           0  
14           0  
15           0  
16           0  
17           0  
18           0  
19           0  
20           0  
21           0  
22           0  
23           0  
24           0  
25           0  
26           0  
27           0  
28           0  
29           0  
30           0  
31           0  
32           0  
33           0

In [295]:
df.drop(columns="Percentage",inplace=True)

In [304]:
df[1]=["krishna",11,90,40,50,60,55,295,0]

ValueError: Length of values does not match length of index

In [300]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
dtype: bool

In [305]:
df

Name  Roll_no  Telugu  English  Maths  Science  Social  Marks
0      krishna       11      90       40     50       60      55    295
1        gunnu       12      90       41     51       61      56    299
2        mouni       13      30       42     52       62      57    243
3        vamsi       14      40       43     53       63      58    257
4      manohar       15      20       44     54       64      59    241
5        laxmi       16      29       45     55       65      60    254
6        vijay       17      49       46     56       66      61    278
7       rajesh       18      48       47     57       67      62    281
8        krish       19      59       48     58       68      63    296
9      mounika       20      69       49     59       69      64    310
10         sai       21      60       50     60       70      65    305
11       padma       22      70       51     61       71      66    319
12       divya       23      71       52     62       72      67    324
13      sharmi       24      72       53     63       73      68    329
14        manu       25      73       54     64       74      69    334
15       kumar       26      74       55     65       75      70    339
16        anju       27      75       56     66       76      71    344
17     keerthi       28      76       57     67       77      72    349
18     thanuja       29      77       58     68       78      73    354
19       priya       30      78       59     69       79      74    359
20     likitha       31      79       60     70       80      75    364
21     nikitha       32      80       61     71       81      76    369
22  prathyusha       33      81       62     72       82      77    374
23       bindu       34      82       63     73       83      78    379
24      sandya       35      83       64     74       84      79    384
25      kumari       36      84       65     75       85      80    389
26   sai priya       37      85       66     76       86      81    394
27       kiran       38      86       67     77       87      82    399
28      charan       39      87       68     78       88      83    404
29     chnadra       40      88       69     79       89      84    409
30    kamakshi       41      89       70     80       90      85    414
31     sirisha       42      90       71     81       91      86    419
32      jyothi       43      91       72     82       92      87    424
33      kusuma       44      92       73     83       93      88    429